server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: true

spring:
  elasticsearch:
    uris:
      - https://34.72.131.199:9200
    username: elastic
    password: KPHtrb79V8d20w27dD3bI7X1
    connection-timeout: 120s
    socket-timeout: 60s
    restclient:
      sniffer:
        interval: 5m

logging:
  level:
    tracer: TRACE
