server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: true

spring:
  elasticsearch:
    uris:
      - http://35.192.0.68:9200
    username:
    password:
    connection-timeout: 120s
    socket-timeout: 60s
    restclient:
      sniffer:
        interval: 5m
  data:
    elasticsearch:
      cluster-nodes: 35.192.0.68:9200
      cluster-name: elasticsearch
      repositories:
        enabled: true





logging:
  level:
    tracer: TRACE
